**Importing the Libraries**

In [130]:
import pandas as pd
import numpy as np
import pickle
import matplotlib.pyplot as plt 
import seaborn as sns
import sklearn
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score

**Reading the Processed Dataset**

In [131]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='z1g_Nc6Bi9O_LZV6lU-LcNYZ7Q7rDMVaMS8VSJZjBnwD',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.private.us.cloud-object-storage.appdomain.cloud')

bucket = 'smartlenderapplicantcredibilitypr-donotdelete-pr-jutfj1h7iovjbs'
object_key = 'loan_approval_dataset.csv'

body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

final_df = pd.read_csv(body)
final_df.head()


Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        1           0          0              0         8.699515   
1       1        1           0          0              0         7.992269   
2       1        1           2          0              0         8.740337   
3       1        1           0          0              0         7.641564   
4       1        0           0          0              0         8.334712   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0             2250.0    5.579730             360.0               1   
1             2900.0    4.875197             360.0               1   
2             1695.0    5.347108             360.0               1   
3             3150.0    4.852030             360.0               1   
4                0.0    4.584967             360.0               0   

   Property_Area  Loan_Status  
0              1            0  
1              1            1  
2              1            1  
3              1            1  
4              1            0

In [132]:
final_df

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0         1        1           0          0              0         8.699515   
1         1        1           0          0              0         7.992269   
2         1        1           2          0              0         8.740337   
3         1        1           0          0              0         7.641564   
4         1        0           0          0              0         8.334712   
..      ...      ...         ...        ...            ...              ...   
486       1        1           2          1              1         7.536364   
487       1        1           2          0              0         9.342859   
488       0        0           0          0              0         8.082402   
489       0        1           0          0              0         9.215029   
490       1        1           0          0              0         9.521495   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0               2250.0    5.579730             360.0               1   
1               2900.0    4.875197             360.0               1   
2               1695.0    5.347108             360.0               1   
3               3150.0    4.852030             360.0               1   
4                  0.0    4.584967             360.0               0   
..                 ...         ...               ...             ...   
486             1875.0    4.574711             360.0               1   
487             1126.0    5.416100             360.0               1   
488                0.0    3.401197             360.0               1   
489                0.0    4.857444             240.0               1   
490                0.0    4.857444             360.0               1   

     Property_Area  Loan_Status  
0                1            0  
1                1            1  
2                1            1  
3                1            1  
4                1            0  
..             ...          ...  
486              1            1  
487              2            1  
488              2            1  
489              1            1  
490              2            1  

[491 rows x 12 columns]

In [133]:
y_train=y_train.map({1:'Y',0:'N'})
# @hidden_cell
# The following code contains the credentials for a file in your IBM Cloud Object Storage.
# You might want to remove those credentials before you share your notebook.
metadata_1 = {
    'IAM_SERVICE_ID': 'iam-ServiceId-62fff7bd-aa1c-43b1-b644-ba4b97280ee9',
    'IBM_API_KEY_ID': 'z1g_Nc6Bi9O_LZV6lU-LcNYZ7Q7rDMVaMS8VSJZjBnwD',
    'ENDPOINT': 'https://s3.private.us.cloud-object-storage.appdomain.cloud',
    'IBM_AUTH_ENDPOINT': 'https://iam.cloud.ibm.com/oidc/token',
    'BUCKET': 'smartlenderapplicantcredibilitypr-donotdelete-pr-jutfj1h7iovjbs',
    'FILE': 'loan_prediction.csv'
}
y_test=y_test.map({1:'Y',0:'N'})

In [134]:
final_df.isna().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

**Splitting as Training and Testing Data**

In [135]:
from sklearn.model_selection import train_test_split
train,test = train_test_split(final_df, test_size=0.33, random_state=42)

In [136]:
x=final_df.drop(["Loan_Status"],axis=1)
y=final_df.Loan_Status
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

# **Model Building**

**Decision Tree Model**

In [137]:
def decisionTree(x_train, x_test, y_train, y_test):
    dt=DecisionTreeClassifier() 
    dt.fit(x_train,y_train) 
    yPred = dt.predict(x_test)
    print('***DecisionTreeClassifier***') 
    print('Confusion matrix')
    print(confusion_matrix(y_test,yPred)) 
    print('Classification report') 
    print(classification_report (y_test,yPred))
    print("score")
    print(dt.score(x_test,y_test))

**Random Forest Model**

In [138]:
def randomForest(x_train, x_test, y_train, y_test):
    rf = RandomForestClassifier() 
    rf.fit(x_train,y_train) 
    yPred = rf.predict(x_test) 
    print('***RandomForestClassifier***') 
    print('Confusion matrix')
    print(confusion_matrix(y_test,yPred))
    print('Classification report')
    print(classification_report(y_test,yPred))
    print("score")
    print(rf.score(x_test,y_test))

**KNN**

In [139]:
def KNN(x_train, x_test, y_train, y_test):
    knn = KNeighborsClassifier()
    knn.fit(x_train,y_train)
    yPred = knn.predict(x_test)
    print('***KNeighborsClassifier***') 
    print('Confusion matrix')
    print(confusion_matrix(y_test,yPred)) 
    print('Classification report')
    print(classification_report(y_test,yPred))
    print("score")
    print(knn.score(x_test,y_test))

**XG Boost Model**




In [140]:
def xgboost(x_train, x_test, y_train, y_test):
    xg = GradientBoostingClassifier()
    xg.fit(x_train,y_train)
    yPred = xg.predict(x_test)
    print('***Gradient BoostingClassifier***') 
    print('Confusion matrix')
    print(confusion_matrix(y_test,yPred)) 
    print('Classification report')
    print(classification_report(y_test,yPred))
    print("score")
    print(xg.score(x_test,y_test))

**Comparing the Models**

In [141]:
decisionTree(x_train, x_test, y_train, y_test)

***DecisionTreeClassifier***
Confusion matrix
[[14 19]
 [10 56]]
Classification report
              precision    recall  f1-score   support

           0       0.58      0.42      0.49        33
           1       0.75      0.85      0.79        66

    accuracy                           0.71        99
   macro avg       0.67      0.64      0.64        99
weighted avg       0.69      0.71      0.69        99

score
0.7070707070707071


In [142]:
from sklearn.ensemble import RandomForestClassifier
randomForest(x_train, x_test, y_train, y_test)

***RandomForestClassifier***
Confusion matrix
[[11 22]
 [ 5 61]]
Classification report
              precision    recall  f1-score   support

           0       0.69      0.33      0.45        33
           1       0.73      0.92      0.82        66

    accuracy                           0.73        99
   macro avg       0.71      0.63      0.63        99
weighted avg       0.72      0.73      0.70        99

score
0.7272727272727273


In [143]:
KNN(x_train, x_test, y_train, y_test)

***KNeighborsClassifier***
Confusion matrix
[[ 4 29]
 [11 55]]
Classification report
              precision    recall  f1-score   support

           0       0.27      0.12      0.17        33
           1       0.65      0.83      0.73        66

    accuracy                           0.60        99
   macro avg       0.46      0.48      0.45        99
weighted avg       0.53      0.60      0.54        99

score
0.5959595959595959


In [144]:
from sklearn.ensemble import GradientBoostingClassifier
xgboost(x_train, x_test, y_train, y_test)

***Gradient BoostingClassifier***
Confusion matrix
[[12 21]
 [ 6 60]]
Classification report
              precision    recall  f1-score   support

           0       0.67      0.36      0.47        33
           1       0.74      0.91      0.82        66

    accuracy                           0.73        99
   macro avg       0.70      0.64      0.64        99
weighted avg       0.72      0.73      0.70        99

score
0.7272727272727273


**Evaluating Performance of the Model and Saving the model**

In [146]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(x_train,y_train)
yPred = rf.predict(x_test)
f1_score(yPred,y_test, average='weighted')
cv = cross_val_score(rf,x,y,cv=5)
np.mean(cv)

0.8002886002886005

In [147]:
!pip install -U ibm-watson-machine-learning

In [162]:
from ibm_watson_machine_learning import APIClient
import json

In [163]:
wml_credentials = {
    "apikey" : "OVk_2Ft8CV8IyLf1-x_OMFJIsbmSOO6Kk8-QIw43Maub",
    "url" : "https://us-south.ml.cloud.ibm.com"
}

In [164]:
wml_client = APIClient(wml_credentials)

In [165]:
wml_client.spaces.list()

Note: 'limit' is not provided. Only first 50 records will be displayed if the number of records exceed 50
------------------------------------  ------------------  ------------------------
ID                                    NAME                CREATED
03a04cdb-e1a9-42ae-8c05-49925ff61831  Models Deployments  2022-11-18T22:41:14.803Z
------------------------------------  ------------------  ------------------------


In [166]:
def guid_from_space_name(client, space_name):
    space = client.spaces.get_details()
    return(next(item for item in space['resources'] if item['entity']['name'] == space_name)['metadata']['id'])

In [174]:
SPACE_ID="03a04cdb-e1a9-42ae-8c05-49925ff61831"

In [175]:
wml_client.set.default_space(SPACE_ID)

'SUCCESS'

In [176]:
import sklearn
sklearn.__version__

'1.0.2'

In [177]:
MODEL_NAME = 'Model_building_SL_223_IBM'
DEPLOYMENT_NAME = 'Smart-Lender_223_IBM'
DEMO_MODEL = rf

In [181]:
software_spec_uid = wml_client.software_specifications.get_id_by_name('runtime-22.1-py3.9')
software_spec_uid 

'12b83a17-24d8-5082-900f-0ab31fbfd3cb'

In [190]:
model_props = {
    wml_client.repository.ModelMetaNames.NAME: "loan_approval_model", 
    wml_client.repository.ModelMetaNames.TYPE: 'scikit-learn_1.0', 
    wml_client.repository.ModelMetaNames.SOFTWARE_SPEC_UID: software_spec_uid 
}

In [191]:
model_details = wml_client.repository.store_model(
    model=DEMO_MODEL, 
    meta_props=model_props, 
    training_data=x_train, 
    training_target=y_train
)

In [192]:
model_details

{'entity': {'hybrid_pipeline_software_specs': [],
  'label_column': 'Loan_Status',
  'schemas': {'input': [{'fields': [{'name': 'Gender', 'type': 'int64'},
      {'name': 'Married', 'type': 'int64'},
      {'name': 'Dependents', 'type': 'int64'},
      {'name': 'Education', 'type': 'int64'},
      {'name': 'Self_Employed', 'type': 'int64'},
      {'name': 'ApplicantIncome', 'type': 'float64'},
      {'name': 'CoapplicantIncome', 'type': 'float64'},
      {'name': 'LoanAmount', 'type': 'float64'},
      {'name': 'Loan_Amount_Term', 'type': 'float64'},
      {'name': 'Credit_History', 'type': 'int64'},
      {'name': 'Property_Area', 'type': 'int64'}],
     'id': '1',
     'type': 'struct'}],
   'output': []},
  'software_spec': {'id': '12b83a17-24d8-5082-900f-0ab31fbfd3cb',
   'name': 'runtime-22.1-py3.9'},
  'type': 'scikit-learn_1.0'},
 'metadata': {'created_at': '2022-11-18T23:04:00.585Z',
  'id': 'a6333a39-72dd-40d4-b2d2-db9ca4a8c40c',
  'modified_at': '2022-11-18T23:04:03.315Z',
  

In [193]:
model_id = wml_client.repository.get_model_id(model_details)
model_id

'a6333a39-72dd-40d4-b2d2-db9ca4a8c40c'

In [194]:
deployment_props = {
    wml_client.deployments.ConfigurationMetaNames.NAME:DEPLOYMENT_NAME, 
    wml_client.deployments.ConfigurationMetaNames.ONLINE: {}
}

In [204]:
deployment = wml_client.deployments.create(
    artifact_uid=model_id, 
    meta_props=deployment_props 
)



#######################################################################################

Synchronous deployment creation for uid: 'a6333a39-72dd-40d4-b2d2-db9ca4a8c40c' started

#######################################################################################


initializing
Note: online_url is deprecated and will be removed in a future release. Use serving_urls instead.
.
ready


------------------------------------------------------------------------------------------------
Successfully finished deployment creation, deployment_uid='e3fa7550-62aa-412f-a1e3-ee1338753be6'
------------------------------------------------------------------------------------------------


