# PROJECT NAME: Smart lender Applicant credibility prediction for loan approval

### TEAM MEMBERS:

## MEMBER 01 : BIJAY KUMAR CHAUDHARY
## MEMBER 02 : SHIVDASH AGRAHARI BANIYA
## MEMBER 03 : MOHANRAJ A
## MEMBER 04 : MOHANRAJ R

# Model_Building

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MaxAbsScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score
from sklearn.metrics import f1_score
import pickle

In [2]:
scaler = MaxAbsScaler()

In [3]:
#train dataset
train = pd.read_csv('train.csv')

In [4]:
#test dataset
test = pd.read_csv('test.csv')

In [5]:
train.head()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        1           0          0              0             6000   
1       1        1           0          0              0             2958   
2       1        1           2          0              0             6250   
3       1        1           0          0              0             2083   
4       1        0           0          0              0             4166   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0             2250.0       265.0             360.0             1.0   
1             2900.0       131.0             360.0             1.0   
2             1695.0       210.0             360.0             1.0   
3             3150.0       128.0             360.0             1.0   
4                0.0        98.0             360.0             0.0   

   Property_Area  Loan_Status  
0              1            0  
1              1            1  
2              1            1  
3              1            1  
4              1            0

In [7]:
train_y = train.iloc[:,-1]

In [8]:
train_x = train.drop('Loan_Status',axis=1)

In [9]:
test_y = test.iloc[:,-1]

In [10]:
test_x = test.drop('Loan_Status',axis=1)

In [11]:
x = pd.concat([train_x,test_x],axis=0)
y = pd.concat([train_y,test_y],axis=0)

In [12]:
train_x = scaler.fit_transform(train_x)

In [13]:
test_x = scaler.transform(test_x)

1.Decision tree model

In [14]:
def decisionTree(train_x,test_x,train_y,test_y):
    dt = DecisionTreeClassifier()
    dt.fit(train_x,train_y)
    y_pred = dt.predict(test_x)
    print("**** Decision Tree Classifier ****")
    print('Confusion Matrix')
    print(confusion_matrix(test_y,y_pred))
    print('Classification Report')
    print(classification_report(test_y,y_pred))

2.Random forest model

In [16]:
def randomForest(train_x,test_x,train_y,test_y):
    rf = RandomForestClassifier()
    rf.fit(train_x,train_y)
    y_pred = rf.predict(test_x)
    print("**** Random Forest Classifier ****")
    print('Confusion Matrix')
    print(confusion_matrix(test_y,y_pred))
    print('Classification Report')
    print(classification_report(test_y,y_pred))

3.K-nearest Neighbor model

In [17]:
def knn(train_x,test_x,train_y,test_y):
    knn = KNeighborsClassifier()
    knn.fit(train_x,train_y)
    y_pred = knn.predict(test_x)
    print("**** KNeighbour Classifier ****")
    print('Confusion Matrix')
    print(confusion_matrix(test_y,y_pred))
    print('Classification Report')
    print(classification_report(test_y,y_pred))

4.Xgboost model

In [18]:
def xgboost(train_x,test_x,train_y,test_y):
    xg = GradientBoostingClassifier()
    xg.fit(train_x,train_y)
    y_pred = xg.predict(test_x)
    print("**** Gradient Boosting Classifier ****")
    print('Confusion Matrix')
    print(confusion_matrix(test_y,y_pred))
    print('Classification Report')
    print(classification_report(test_y,y_pred))

Compare all the models

In [19]:
decisionTree(train_x,test_x,train_y,test_y)

**** Decision Tree Classifier ****
Confusion Matrix
[[23 20]
 [18 62]]
Classification Report
              precision    recall  f1-score   support

           0       0.56      0.53      0.55        43
           1       0.76      0.78      0.77        80

    accuracy                           0.69       123
   macro avg       0.66      0.65      0.66       123
weighted avg       0.69      0.69      0.69       123



In [20]:
randomForest(train_x,test_x,train_y,test_y)

**** Random Forest Classifier ****
Confusion Matrix
[[18 25]
 [ 3 77]]
Classification Report
              precision    recall  f1-score   support

           0       0.86      0.42      0.56        43
           1       0.75      0.96      0.85        80

    accuracy                           0.77       123
   macro avg       0.81      0.69      0.70       123
weighted avg       0.79      0.77      0.75       123



In [21]:
knn(train_x,test_x,train_y,test_y)

**** KNeighbour Classifier ****
Confusion Matrix
[[18 25]
 [ 5 75]]
Classification Report
              precision    recall  f1-score   support

           0       0.78      0.42      0.55        43
           1       0.75      0.94      0.83        80

    accuracy                           0.76       123
   macro avg       0.77      0.68      0.69       123
weighted avg       0.76      0.76      0.73       123



In [22]:
xgboost(train_x,test_x,train_y,test_y)

**** Gradient Boosting Classifier ****
Confusion Matrix
[[19 24]
 [ 6 74]]
Classification Report
              precision    recall  f1-score   support

           0       0.76      0.44      0.56        43
           1       0.76      0.93      0.83        80

    accuracy                           0.76       123
   macro avg       0.76      0.68      0.70       123
weighted avg       0.76      0.76      0.74       123



In [23]:
#Knn model is selected
knn = KNeighborsClassifier()
knn.fit(train_x,train_y)
y_pred = knn.predict(test_x)

In [25]:
f1_score(y_pred,test_y,average='weighted')

0.7795023404779503

In [26]:
cv = cross_val_score(knn,x,y,cv=5)

In [27]:
np.mean(cv)

0.6253898440623751

In [28]:
pickle.dump(knn,open('rdf.pkl','wb'))
pickle.dump(scaler,open('scale.pkl','wb'))