**Importing the Libraries**

In [3]:
import pandas as pd
import numpy as np
import pickle
import matplotlib.pyplot as plt 
import seaborn as sns
import sklearn
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score

**Reading the Processed Dataset**

In [5]:
final_df=pd.read_csv('loan_approval_dataset.csv')

In [6]:
final_df

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0         0        0           0          0              0             2995   
1         1        1           3          0              0             9504   
2         1        0           0          0              0             3600   
3         1        1           2          0              0             3283   
4         1        1           1          0              0             7250   
..      ...      ...         ...        ...            ...              ...   
689       0        0           0          0              0             2393   
690       1        1           2          1              0             3601   
691       1        1           0          0              0             3000   
692       0        0           0          0              0             2378   
693       1        1           0          1              0             1863   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                    0          60               360               1   
1                    0         275               360               1   
2                    0          80               360               1   
3                 2035         148               360               1   
4                 1667         110               360               0   
..                 ...         ...               ...             ...   
689                  0          19               375               1   
690               1590         120               360               1   
691               3416          56               180               1   
692                  0          46               360               1   
693               1041          98               360               1   

     Property_Area  Loan_Status  
0                2            1  
1                0            1  
2                2            0  
3                2            1  
4                2            0  
..             ...          ...  
689              1            0  
690              0            1  
691              1            1  
692              0            0  
693              1            1  

[694 rows x 12 columns]

**Splitting as Training and Testing Data**

In [7]:
train,test = train_test_split(final_df, test_size=0.33, random_state=42)

In [9]:
x=final_df.drop(["Loan_Status"],axis=1)
y=final_df.Loan_Status
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

# **Model Building**

**Decision Tree Model**

In [10]:
def decisionTree(x_train, x_test, y_train, y_test):
    dt=DecisionTreeClassifier() 
    dt.fit(x_train,y_train) 
    yPred = dt.predict(x_test)
    print('***DecisionTreeClassifier***') 
    print('Confusion matrix')
    print(confusion_matrix(y_test,yPred)) 
    print('Classification report') 
    print(classification_report (y_test,yPred))
    print("score")
    print(dt.score(x_test,y_test))

**Random Forest Model**

In [11]:
def randomForest(x_train, x_test, y_train, y_test):
    rf = RandomForestClassifier() 
    rf.fit(x_train,y_train) 
    yPred = rf.predict(x_test) 
    print('***RandomForestClassifier***') 
    print('Confusion matrix')
    print(confusion_matrix(y_test,yPred))
    print('Classification report')
    print(classification_report(y_test,yPred))
    print("score")
    print(rf.score(x_test,y_test))

**KNN**

In [12]:
def KNN(x_train, x_test, y_train, y_test):
    knn = KNeighborsClassifier()
    knn.fit(x_train,y_train)
    yPred = knn.predict(x_test)
    print('***KNeighborsClassifier***') 
    print('Confusion matrix')
    print(confusion_matrix(y_test,yPred)) 
    print('Classification report')
    print(classification_report(y_test,yPred))
    print("score")
    print(knn.score(x_test,y_test))

**XG Boost Model**




In [13]:
def xgboost(x_train, x_test, y_train, y_test):
    xg = GradientBoostingClassifier()
    xg.fit(x_train,y_train)
    yPred = xg.predict(x_test)
    print('***Gradient BoostingClassifier***') 
    print('Confusion matrix')
    print(confusion_matrix(y_test,yPred)) 
    print('Classification report')
    print(classification_report(y_test,yPred))
    print("score")
    print(xg.score(x_test,y_test))

**Comparing the Models**

In [14]:
decisionTree(x_train, x_test, y_train, y_test)

***DecisionTreeClassifier***
Confusion matrix
[[64 17]
 [20 38]]
Classification report
              precision    recall  f1-score   support

           0       0.76      0.79      0.78        81
           1       0.69      0.66      0.67        58

    accuracy                           0.73       139
   macro avg       0.73      0.72      0.72       139
weighted avg       0.73      0.73      0.73       139

score
0.7338129496402878


In [15]:
randomForest(x_train, x_test, y_train, y_test)

***RandomForestClassifier***
Confusion matrix
[[57 24]
 [ 8 50]]
Classification report
              precision    recall  f1-score   support

           0       0.88      0.70      0.78        81
           1       0.68      0.86      0.76        58

    accuracy                           0.77       139
   macro avg       0.78      0.78      0.77       139
weighted avg       0.79      0.77      0.77       139

score
0.7697841726618705


In [16]:
KNN(x_train, x_test, y_train, y_test)

***KNeighborsClassifier***
Confusion matrix
[[49 32]
 [20 38]]
Classification report
              precision    recall  f1-score   support

           0       0.71      0.60      0.65        81
           1       0.54      0.66      0.59        58

    accuracy                           0.63       139
   macro avg       0.63      0.63      0.62       139
weighted avg       0.64      0.63      0.63       139

score
0.6258992805755396


In [17]:
xgboost(x_train, x_test, y_train, y_test)

***Gradient BoostingClassifier***
Confusion matrix
[[55 26]
 [ 5 53]]
Classification report
              precision    recall  f1-score   support

           0       0.92      0.68      0.78        81
           1       0.67      0.91      0.77        58

    accuracy                           0.78       139
   macro avg       0.79      0.80      0.78       139
weighted avg       0.81      0.78      0.78       139

score
0.7769784172661871


**Evaluating Performance of the Model and Saving the model**

In [18]:
from sklearn.model_selection import cross_val_score
rf = RandomForestClassifier()
rf.fit(x_train,y_train)
yPred = rf.predict(x_test)
f1_score(yPred,y_test, average='weighted')
cv = cross_val_score(rf,x,y,cv=5)
np.mean(cv)

0.7939526639557919

In [19]:
!pip install -U ibm-watson-machine-learning

In [20]:
from ibm_watson_machine_learning import APIClient
import json

In [21]:
wml_credentials = {
    "apikey" : "yjJRKquYkWeXxU3CGuvFC0Q1f29M8lpidj6PZ8B0RQgY",
    "url" : "https://eu-gb.ml.cloud.ibm.com"
}

In [22]:
wml_client = APIClient(wml_credentials)

In [24]:
wml_client.spaces.list()

Note: 'limit' is not provided. Only first 50 records will be displayed if the number of records exceed 50
------------------------------------  ----------------  ------------------------
ID                                    NAME              CREATED
99b1a4a9-7cc5-4852-9388-f8907fe20de7  sl_223_ibm_space  2022-11-16T10:44:29.321Z
------------------------------------  ----------------  ------------------------


In [25]:
SPACE_ID= "99b1a4a9-7cc5-4852-9388-f8907fe20de7"

In [26]:
wml_client.set.default_space(SPACE_ID)

'SUCCESS'

In [28]:
import sklearn
sklearn.__version__

'1.0.2'

In [29]:
MODEL_NAME = 'Model_building_SL_223_IBM'
DEPLOYMENT_NAME = 'Smart-Lender_223_IBM'
DEMO_MODEL = rf

In [30]:
software_spec_uid = wml_client.software_specifications.get_id_by_name('runtime-22.1-py3.9')

In [31]:
model_props = {
    wml_client.repository.ModelMetaNames.NAME: MODEL_NAME, 
    wml_client.repository.ModelMetaNames.TYPE: 'scikit-learn_1.0', 
    wml_client.repository.ModelMetaNames.SOFTWARE_SPEC_UID: software_spec_uid 
}

In [32]:
model_details = wml_client.repository.store_model(
    model=DEMO_MODEL, 
    meta_props=model_props, 
    training_data=x_train, 
    training_target=y_train
)

In [33]:
model_details

{'entity': {'hybrid_pipeline_software_specs': [],
  'label_column': 'Loan_Status',
  'schemas': {'input': [{'fields': [{'name': 'Gender', 'type': 'int64'},
      {'name': 'Married', 'type': 'int64'},
      {'name': 'Dependents', 'type': 'int64'},
      {'name': 'Education', 'type': 'int64'},
      {'name': 'Self_Employed', 'type': 'int64'},
      {'name': 'ApplicantIncome', 'type': 'int64'},
      {'name': 'CoapplicantIncome', 'type': 'int64'},
      {'name': 'LoanAmount', 'type': 'int64'},
      {'name': 'Loan_Amount_Term', 'type': 'int64'},
      {'name': 'Credit_History', 'type': 'int64'},
      {'name': 'Property_Area', 'type': 'int64'}],
     'id': '1',
     'type': 'struct'}],
   'output': []},
  'software_spec': {'id': '12b83a17-24d8-5082-900f-0ab31fbfd3cb',
   'name': 'runtime-22.1-py3.9'},
  'type': 'scikit-learn_1.0'},
 'metadata': {'created_at': '2022-11-16T10:48:43.132Z',
  'id': '03542d22-55b9-4830-af6f-c000da875e4e',
  'modified_at': '2022-11-16T10:48:46.959Z',
  'name': 

In [34]:
model_id = wml_client.repository.get_model_id(model_details)
model_id

'03542d22-55b9-4830-af6f-c000da875e4e'

In [37]:
deployment_props = {
    wml_client.deployments.ConfigurationMetaNames.NAME:DEPLOYMENT_NAME, 
    wml_client.deployments.ConfigurationMetaNames.ONLINE: {}
}

In [38]:
deployment = wml_client.deployments.create(
    artifact_uid=model_id, 
    meta_props=deployment_props 
)



#######################################################################################

Synchronous deployment creation for uid: '03542d22-55b9-4830-af6f-c000da875e4e' started

#######################################################################################


initializing
Note: online_url is deprecated and will be removed in a future release. Use serving_urls instead.

ready


------------------------------------------------------------------------------------------------
Successfully finished deployment creation, deployment_uid='84569608-2735-48f9-991a-fb61d5a0c2af'
------------------------------------------------------------------------------------------------


